apiVersion: apps/v1
kind: Deployment
metadata:
  name: events
spec:
  template:
    spec:
      containers:
        - name: kube-state-events
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
