apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: winlogs
spec:
  template:
    spec:
      containers:
        - name: fluentd
          resources:
            limits:
              cpu: 200m
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 1024Mi
