apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metrics
  namespace: observe
spec:
  template:
    spec:
      containers:
        - name: grafana-agent
          resources:
            limits:
              cpu: 1
              memory: 8Gi
            requests:
              cpu: 1
              memory: 8Gi
