---
name: Release and push
on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * 2'

jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubectl_version:
          - v1.25.2    # leading edge  (EOL 2023-10-27)
          - v1.22.1    # trailing edge (EOL 2022-10-28)
          - v1.16.1    # laggard       (EOL 2020-04-11)
        node_version:
          - kindest/node:v1.25.2@sha256:9be91e9e9cdf116809841fc77ebdb8845443c4c72fe5218f3ae9eb57fdb4bace
          - kindest/node:v1.21.1@sha256:e0bf222d7dd1589075117c51740903017b328c59ffb0c3d97187a2b3de1f92b3
          - kindest/node:v1.16.1@sha256:1b59f5d62b2f49c439ee29a9146d012b73255169e88f9acaca9e9ba610511380
        kustomize_dir:
          - stack/m
          - stack/xs
          - stack/xl
    steps:
      - uses: actions/checkout@master
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@main
        with:
          kubectl_version: ${{ matrix.kubectl_version }}
          node_image: ${{ matrix.node_version }}
        env:
          KUBE_CONFIG: .kubeconfig
      - name: Test apply
        env:
          OBSERVE_CUSTOMER: ${{ secrets.OBSERVE_CUSTOMER }}
          OBSERVE_TOKEN: ${{ secrets.OBSERVE_TOKEN }}
          KUSTOMIZE_DIR: ${{ matrix.kustomize_dir }}
        run: make apply
      - name: Test delete
        env:
          KUSTOMIZE_DIR: ${{ matrix.kustomize_dir }}
        run: make delete
  bump:
    runs-on: ubuntu-latest
    needs: integration-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          skip-on-empty: 'true'
          skip-version-file: 'true'
      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
